In [1]:
import numpy as np

In [7]:
matrix=np.zeros(3)

In [8]:
matrix

array([0., 0., 0.])

In [9]:
?np.zeros

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [10]:
matrix=np.zeros((3,3))

In [11]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
value=int(input("enter the number:"))

In [17]:
for x in range((3,3)):
    matrix[x,x]=value

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
size=[3,3]
matrix1=np.zeros((size,size),dtype=int)

TypeError: 'list' object cannot be interpreted as an integer

In [20]:
matrix1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
for x in range((3,3)):
    matrix1[x,x]=value

TypeError: 'tuple' object cannot be interpreted as an integer

In [25]:
size=int(input("enter the size of the matrix:"))

In [28]:
matrix3=np.zeros((size,size))

In [29]:
matrix3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
for x in range(size):
    matrix3[x,x]=value 

In [32]:
matrix3

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [35]:
for i in range(size):
    matrix[i,size-i]=value

IndexError: index 3 is out of bounds for axis 1 with size 3

In [36]:
?index 3 is out of bounds for axis 1 with size 3


Object `index 3 is out of bounds for axis 1 with size 3` not found.


In [37]:
for i in range(size):
    matrix3[i,size-i-1]=value

In [38]:
matrix3

array([[4., 0., 4.],
       [0., 4., 0.],
       [4., 0., 4.]])

In [43]:
def matrix_creation(size,value):
    mat=np.zeros((size,size))
    for x in range(size):
        mat[x,x]=value
    for i in range(size):
        mat[i,size-i-1]=value
    size=int(input("enter the size for the matrix:"))
    value=int(input("enter the number for the diagonals of the matrix:"))
matrix_creation()

TypeError: matrix_creation() missing 2 required positional arguments: 'size' and 'value'

In [44]:
def matrix_creation(size,value):
    mat=np.zeros((size,size))
    for x in range(size):
        mat[x,x]=value
    for i in range(size):
        mat[i,size-i-1]=value
size=int(input("enter the size for the matrix:"))
value=int(input("enter the number for the diagonals of the matrix:"))
mat=matrix_creation(size,value)

In [ ]:
mat

In [41]:
def matrix_creation(size,value):
    mat=np.zeros((size,size))
    for x in range(size):
        mat[x,x]=value
    for i in range(size):
        mat[i,size-i-1]=value
    return mat
size=int(input("enter the size for the matrix:"))
value=int(input("enter the number for the diagonals of the matrix:"))
mat=matrix_creation(size,value)

In [42]:
mat

array([[7., 0., 7.],
       [0., 7., 0.],
       [7., 0., 7.]])